export const ipcChannels = {
  IMAGE_LOAD: 'IMAGE_LOAD',
  GET_HOST_IP_ADDRESS: 'GET_HOST_IP_ADDRESS',
  LOAD_SETTING: 'LOAD_SETTING',
  START_PROXY_SERVER: 'START_PROXY_SERVER',
  STOP_PROXY_SERVER: 'STOP_PROXY_SERVER',
}
